title: Amena Mahdami
description: Welcome to my portfolio! Here, you will find highlights of my programming skills applied in Bioinformatics through showcasing selected projects.
show_downloads: false
theme: jekyll-theme-minimal

