title: Amena Mahdami
#logo: daisy.png
description: This portfolio highlights my programming skills applied in the fields of Bioinformatics and Data Science through showcasing selected projects.
show_downloads: true
theme: jekyll-theme-minimal

