title: Amena Mahdami
description: |
Welcome to my portfolio! Here, you will find highlights of my programming skills applied in the fields of Bioinformatics and Data Science through showcasing selected projects.
show_downloads: false
theme: jekyll-theme-minimal

